version: '3.9'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: apiinfluencers-app
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mongo
    container_name: apiinfluencers-db
    restart: always
    tty: true
    ports:
      - "27017:27017"
    volumes:
      - .docker/dbdata:/var/lib/mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: apiinfluencers-mongoexpress
    tty: true
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: marlon
      ME_CONFIG_BASICAUTH_PASSWORD: marlon
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    ports:
      - 8081:8081
    depends_on:
      - db